services:
  mariadb:
    container_name: vista-mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - vista-network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 40s

  phpmyadmin:
    container_name: vista-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:888:80"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - vista-network

  flask_app:
    container_name: vista-flask
    build: .
    restart: always
    environment:
      DATABASE_URI: ${DATABASE_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY}
      DEBUG: ${DEBUG}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - flask_migrations:/app/migrations
      - flask_uploads:/app/uploads
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - vista-network
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
    driver: local
  flask_migrations:
    driver: local
  flask_uploads:
    driver: local


networks:
  vista-network:
      driver: bridge
