from .auth import auth_bp
from .backup import backup_bp
from .profile import profile_bp
from .quest import quest_bp
from .quest_progress import progress_bp
from .rating import rating_bp
from .stats import stats_bp
from .task import task_bp
from .user import user_bp
